backgrounds:
  diboson:
    file: /Users/ptiwari/Development/EventGen/DelphesBackground/diboson_delphes_events.root
  sTop_tchannel:
    file: /Users/ptiwari/Development/EventGen/DelphesBackground/sTop_tchannel_delphes_events.root
  sTop_tW:
    file: /Users/ptiwari/Development/EventGen/DelphesBackground/sTop_tW_delphes_events.root
  ttbar:
    file: /Users/ptiwari/Development/EventGen/DelphesBackground/ttbar_delphes_events.root
  wlnjets:
    file: /Users/ptiwari/Development/EventGen/DelphesBackground/wlnjets_delphes_events.root
  znnjets:
    file: /Users/ptiwari/Development/EventGen/DelphesBackground/znnjets_delphes_events.root
  dyjets:
    file: /Users/ptiwari/Development/EventGen/DelphesBackground/dyjets_delphes_events.root
